on:
  push:

jobs:
  ide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - run: npm ci
        working-directory: ide
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}
      - name: Use OCaml
        with:
          ocaml-compiler: 4.14.0
          dune-cache: true
          allow-prerelease-opam: true
        env:
          OPAMLOCKED: locked
        uses: ocaml/setup-ocaml@v3
      - run: opam install . --deps-only
      - run: opam exec -- dune build
